config/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views 
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index),
    path('login/',views.Login.as_view()),
    path('task_main/',views.task_main),
    path('logout/',LogoutView.as_view()),
    path('extends_block_test/',views.extends_block_test),
    path('report/',include('report.urls')),#report
    path('js_test/',include('js_test.urls')),#js_test
]

js_test/urls.py
from django.urls import path,include
from js_test import views

urlpatterns = [
    path('length/',views.length),#inputタグのnumber属性の入力数制限
    path('callback/',views.callback),#callback関数
    path('unsync/',views.unsync),#非同期通信
    path('prep1/',views.prep1),#予習用
    path('prep2/',views.prep2),#予習用
    path('prep3',views.prep3),#予習用
    path('test1/',views.test1),#当日教材用
    path('test2/',views.test2),#当日教材用
    path('test3/',views.test3),#当日教材用
    path('test4/',views.test4),#当日教材用
    path('basic1/',views.basic1),#勉強会後ともスタに沿った物
    path('basic2/',views.basic2),#勉強会後ともスタに沿った物
    path('basic3/',views.basic3),#勉強会後ともスタに沿った物
    path('basic3-1/',views.basic3_1),#勉強会後ともスタに沿った物
    path('basic3-2/',views.basic3_2),#Ajax通信のところ
    path('jq1/',views.jq1),#jQueryの学習
    path('vue1/',views.vue1),#Vue.jsの学習
    path('vue2/',views.vue2),#Vue.jsの学習 写真・コメント等
    path('slide1/',views.slide1),#スライドショーを表示
    path('slide2/',views.slide2),#Ajax通信・jQuery・Vue.jsを使ったスライドショー
    path('ani1/',views.ani1),#アニメーションの学習Web Animations API
    path('ani2/',views.ani2),#ともすたWeb Animations API
    path('ani3/',views.ani3),#ぷよぷよアニメーション
]

js_test/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
#BaseUserManager, AbstractBaseUser 新規でPermissionsMixinインポート
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser ,PermissionsMixin
#idの範囲を絞るためにvalidatorsをインポート
from django.core import validators
# Create your models here.

#＊見方2＊django.contrib.auth.modelsのBaseUserManagerを使用
#テーブル名はUserManager
class UserManager(BaseUserManager):
    #一般ユーザーを作るときのメソッド
    #def create_user(self,id,username, email, password=None):
    def create_user(self,username, email, password=None):
        #idとusernameのValueErrorを追加 
        #ここも削除か
        #if not id:
            #raise ValueError('Users must have an id')
        if not username:
            raise ValueError('Users must have an username')
        #emailがない場合のチェック
        if not email:
            raise ValueError('Users must have an email address')
        #emailがある場合はuserのemailとpasswordを登録する
        #上にidとusernameを追加
        user = self.model(
            #id入らない
            #id=id,
            username=username,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    #スーパーユーザーを作るときのメソッド
    #この後コマンドラインでスーパーユーザーを作成して
    #emailとpasswordで管理画面にログインできるようにする
    #idとusernameを追加
    #def create_superuser(self,id,username, email, password=None):
    def create_superuser(self,username, email, password=None):
        user = self.create_user(
            #idいらない
            #id=id,
            username=username,
            email=self.normalize_email(email),
            password=password,
        )
        #ここで管理画面に入れるようにしている
        user.is_admin = True
        #user.is_staff = True
        #.is_superuserを追加
        user.is_superuser= True
        user.save(using=self._db)
        return user

#＊見方1＊django.contrib.auth.modelsからAbstractBaseUserを呼び出している
#AbstractBaseUserはユーザーモデルの中でも柔軟性が高い。ただし
#コード量が増える。テーブル名はUser
class User(AbstractBaseUser,PermissionsMixin):
    #idの要素を追加int型としてオートインクリメントとしない
    #id要らない
    '''
    id = models.IntegerField(
        blank=False,
        null=False,
        primary_key=True,
        unique=True,
        validators=[validators.MinValueValidator(1),
                    validators.MaxValueValidator(999)]
    )
    '''
    #username(名前)の追加
    username = models.CharField(max_length=10, unique=True,)
    
    #emailのフィールド
    email = models.EmailField(
        max_length=255,
        #emailが被らないようにしている
        unique=True,
    )
    #アカウントがあればログインできる(Web画面)
    is_active = models.BooleanField(default=True)
    
    #スタッフ権限で管理画面に入れるかを追加
    is_staff = models.BooleanField(default=False)
    
    #管理画面にログインできるか
    is_admin = models.BooleanField(default=False)
    #クラスUserManagerをインスタンス化
    objects = UserManager()
    #デフォルトの管理画面のユーザー名をemailとする
    #管理画面の上、ようこそ(hello)の後に続く文字列
    #また、管理画面ログインフォームのusernameの部分→やっぱりemailとする
    USERNAME_FIELD = 'email'
    
    #USERNAME_FIELD = 'username'

    #ターミナルでのスーパーユーザー作成時にemailとpasswordの他
    #に入力を促す項目にidとusernameを追加
    #ここのidもいらない
    #REQUIRED_FIELDS = ['id','username',]
    REQUIRED_FIELDS = ['username',]
    #REQUIRED_FIELDS = ['id','email',]
    #ここら辺は今はこんな感じだと思えば良いです
    #管理画面でモデルUserからusernameを選択すると
    #トップにusernameとidで表示する
    def __str__(self):
        #return self.email
        #ここのidもいらない
        #return f"{self.username} {self.id}"
        return self.username
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

report/models.py
#from tkinter import CASCADE
from tkinter import CASCADE
from django.db import models
#バリデーター
from django.core import validators
#Userモデルの呼び出し
from django.contrib.auth import get_user_model
#Profileモデルの呼び出し
from main.models import Profile

# Create your models here.

#支出のモデル
class Cost(models.Model):
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    seireki = models.IntegerField(null=False,blank=False,validators=[validators.MinValueValidator(200001),validators.MaxValueValidator(299912)])
    koutuuhi = models.IntegerField(default=0,null=False,blank=False)
    shokuhi = models.IntegerField(default=0,null=False,blank=False)
    youfukuhi = models.IntegerField(default=0,null=False,blank=False)
    zeikinn = models.IntegerField(default=0,null=False,blank=False)
    hoken = models.IntegerField(default=0,null=False,blank=False)
    kounetuhi = models.IntegerField(default=0,null=False,blank=False)
    yachin = models.IntegerField(default=0,null=False,blank=False)
    chuushajoudai = models.IntegerField(default=0,null=False,blank=False)
    zapi = models.IntegerField(default=0,null=False,blank=False)
    total = models.IntegerField(null=False,blank=False)
    '''
    def __str__(self):
        #return self.email
        #ここのidもいらない
        return f"{self.username} (番号は{self.member_number}です。)"
        #return self.member_number
    '''

#収入のモデル 
class Incomes(models.Model):
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    seireki = models.IntegerField(null=False,blank=False,validators=[validators.MinValueValidator(200001),validators.MaxValueValidator(299912)])
    salary = models.IntegerField(default=0,null=False,blank=False)
    bonus = models.IntegerField(default=0,null=False,blank=False)
    temporary_income = models.IntegerField(default=0,null=False,blank=False)
    total = models.IntegerField(null=False,blank=False)
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.username}の{self.seireki}収入です"
    

#-----models.forms.admin.urls.views.htmlの統合練習用----

class test1(models.Model):
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    walks = models.IntegerField(default=0,null=False,blank=False,)
    insert_day = models.DateField(help_text='記入日')
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.username}の{self.insert_day}の歩いた歩数です"


#借方モデル←
class Debit(models.Model):
    debit_item = models.CharField(max_length=100)
    
    def __str__(self):
        return f"借方項目は{self.debit_item}です"   

#貸方モデル→
class Credit(models.Model):
    credit_item = models.CharField(max_length=100)
    
    def __str__(self):
        return f"貸方項目は{self.credit_item}です"
    
#仕分けモデル
class Sort(models.Model):
    exec_user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    exec_user_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    exec_day = models.DateField(help_text='仕分実行日')
    debit = models.ForeignKey(Debit,on_delete=models.CASCADE)
    debit_amount = models.IntegerField(null=False,blank=False,)
    credit = models.ForeignKey(Credit,on_delete=models.CASCADE)
    credit_amount = models.IntegerField(null=False,blank=False,)
    comment = models.TextField()
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.exec_day}の{self.comment}の仕分けです"
    
#Costのtotal-Incomeのtotal格納するモデル

###############################################################
#1つのモデルから複数のForeignKeyを使うときは必ずralated_nameを指定する#
###############################################################

#income_totalとcost_totalはreport/views.pyでIncomes,Cost
#モデルでフィルターで値を格納するようにするのでForeignKeyでなく
#IntegerFieldにする(ForeignKeyを使うにはIncomes,Costモデルの
#totalをunique=True,にしなくてはいけなくコレも問題なので)

class Cashbook(models.Model):
    exec_user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name="cashbook_exec_user",)
    exec_user_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",related_name="cashbook_exec_user_number")
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name="cashbook_username")
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",related_name="cashbook_member_number")
    seireki = models.IntegerField(null=False,blank=False,validators=[validators.MinValueValidator(200001),validators.MaxValueValidator(299912)])
    #income_total = models.ForeignKey(Incomes,null=False,blank=False,on_delete=models.CASCADE,to_field="total",) 
    #cost_total = models.ForeignKey(Cost,null=False,blank=False,on_delete=models.CASCADE,to_field="total",)
    income_total = models.IntegerField(null=False,blank=False)
    cost_total = models.IntegerField(null=False,blank=False)
    total = models.IntegerField(null=False,blank=False)
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.seireki}の{self.username}さんの収支です。実行者は{self.exec_user}です"



#-----models.forms.admin.urls.views.htmlの統合練習用----

    
    
#Chatgtpからのdef __str__関数(特殊関数)の練習用のモデル
class Testchatgtp(models.Model):
    name = models.CharField(max_length=15)
    age = models.IntegerField()
    
    #特殊関数__str__は管理画面などで作成された
    #”モデル名 object”をここで他の文字列で表示します。
    #今回の場合だと作成されたオブジェクト(レコード)に
    #名前と年齢を表示します。
    def __str__(self):
        return f"{self.name} (年齢は{self.age}です)"

js_test/views.py
from django.shortcuts import render,redirect

#メッセージを表示するライブラリーをインポート
from django.contrib import messages

#リクエストやURLの検証をするurllibをインポートしてrequestとparseをインポート
from urllib import request,parse

#sslとjsonをインポート
import json,ssl

#環境変数からyamlファイルを呼び出せるようにosをインポート
import os

import datetime

# Create your views here.

#inputタグのnumber属性の場合の入力数の制限
def length(request):
    context = {}
    return render(request,'js_test/length.html',context)

#reCAPTCHAのトークンを検証する関数
def grecaptch_request(token):
    #sslのバージョンを指定
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    #reCAPTCHAapiのURLを記述
    url = "https://www.google.com/recaptcha/api/siteverify"
    #リクエストを送るヘッダーを用意する。{}内は丸写し 
    headers = {'content-type' : 'application/x-www-form-urlencoded'} 
    #シークレットキーとトークンを格納 
    #公式ドキュメントからの流用。キーは丸写し 
    data = { 
    'secret' : os.environ['GRECAPTCHA_SECRETKEY'], 
    'response' : token, 
    } 
    #dataを検証して再度dataとする 
    data = parse.urlencode(data).encode() 
    #urllibのrequestを使って各値をリクエストをします 
    req = request.Request( 
    url, 
    method="POST", 
    headers=headers, 
    data=data, 
    ) 
    #reqをcontext(ssl)で開く 
    f = request.urlopen(req,context=context) 
    #jsonでfで開いて格納 
    response = json.loads(f.read()) 
    #f閉じる 
    f.close() 
    #戻ってきたresponseの中にキーで'success'があるのでそれを返す 
    #TrueかFalseが帰ってくる 
    return response['success']

#callback関数
def callback(request):
    context = {
            'grecaptcha_sitekey': os.environ['GRECAPTCHA_SITEKEY'],
    }
    if request.method == 'POST':
        #-----reCAPTCHA検証----------
        recaptcha_token = request.POST.get("g-recaptcha-response")
        res = grecaptch_request(recaptcha_token)
        if not res:
            messages.error(request,'reCAPTCHA FAIL')
            return render(request,'js_test/callback.html',context)
            #-----reCAPTCHA検証----------
    return render(request,'js_test/callback.html',context)

#非同期通信
def unsync(request):
    context = {}
    return render(request,'js_test/unsync.html',context)

#予習用1
def prep1(request):
    now_time = datetime.datetime.now()
    context = {
        'now_time' : now_time,
    }
    return render(request,'js_test/prep1.html',context)

#予習用2
def prep2(request):
    context = {}
    return render(request,'js_test/prep2.html',context)

#予習用
def prep3(request):
    context = {}
    return render(request,'js_test/prep3.html',context)

#勉強会用
def test1(request):
    context = {}
    return render(request,'js_test/test1.html',context)

#勉強会用
def test2(request):
    context = {}
    return render(request,'js_test/test2.html',context)

#勉強会用
def test3(request):
    context = {}
    return render(request,'js_test/test3.html',context)

#勉強会用
def test4(request):
    context = {}
    return render(request,'js_test/test4.html',context)

#勉強会後の学び直し
def basic1(request):
    context = {
        'now_time' : datetime.datetime.now(),
        'year' : datetime.datetime.now().year,
        'month' : datetime.datetime.now().month,
        'day' : datetime.datetime.now().day,
    }
    return render(request,'js_test/basic1.html',context)

 #勉強会後の学び直し
def basic2(request):
    context = {}
    return render(request,'js_test/basic2.html',context)

#勉強会後の学び直し
def basic3(request):
    context = {}
    return render(request,'js_test/basic3.html',context)

#Djangoでの画面の表示
def basic3_1(request):
    #テンプレートタグfor用
    lists = [1,2,3,4]
    context = {
        "lists" : lists,
    }
    return render(request,'js_test/basic3-1_django-for.html',context)

#Ajax通信
def basic3_2(request):
    context = {}
    return render(request,'js_test/basic3-2_ajax.html',context)

#jQueryの学習
def jq1(request):
    context = {}
    return render(request,'js_test/jq1.html',context)

#Vue.jsの学習
def vue1(request):
    context = {
        'message' : 'どすこいDjango',
    }
    return render(request,'js_test/vue1.html',context)

#Vue.jsの学習 写真・コメント・作成者を表示する
def vue2(request):
    context = {}
    return render(request,'js_test/vue2.html',context)

#スライドショーを表示
def slide1(request):
    context = {}
    return render(request,'js_test/slide1.html',context)

#Ajax通信・jQuery・Vue.jsを使ったスライドショー
def slide2(request):
    context = {}
    return render(request,'js_test/slide2.html',context)

#アニメーションの学習Web Animations API
def ani1(request):
    context = {}
    return render(request,'js_test/ani1.html',context)

#ともすたWeb Animations API
def ani2(request):
    context = {}
    return render(request,'js_test/ani2.html',context)

#ぷよぷよアニメーション
def ani3(request):
    context = {}
    return render(request,'js_test/ani3.html',context)

templates/js_test/callback.html
{# ログイン画面 PHP版組合アプリからの流用 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>callback関数</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>callback関数</h1>
    </div>
    {% comment %}
    <div>
        {% if user.is_authenticated %}
        ログイン中です
        {% else %}
        ログインしていません
        {% endif %}
    </div>
    {% endcomment %}
    <div id="content">
        <div id="lead">
            <p>お疲れ様です。メールアドレスとパスワードでログインして下さい。</p>
            <br>
            <br>
        </div>
        <form action="" method="post">
            {#CSRFトークン発行#}
            {% csrf_token %}
            <dl>
                <dt>メールアドレス</dt>
                <dd>
                    {#typeをemailとしてidを追加 Abstractを使っているのでログインならname="username" 新規登録ならname="email"#}
                    <input type="email" id="id_email" name="username" size="20" maxlength="255" value="" placeholder="Email address" style="height:60px;" required autofocus/>
                    {%comment%}
                    <?php if (isset($error['login']) and $error['login'] === 'blank') :?>
                        <?php //$error['login']を初期化して、blankなら↑ ?>
                        <p class="error">* 組合員番号(下4桁)とパスワードをご記入ください</p>
                    <?php endif; ?>
                    <?php if (isset($error['login']) and $error['login'] === 'failed'): ?>
                        <p class="error">* ログインに失敗しました。正しくご記入ください。</p>
                    <?php endif ;?>
                    {%endcomment%}
                </dd>
                <br>
                {% comment %}
                #クラスLoginViewはメールとパスワードで認証しているのでコメントアウト
                <dt>氏名</dt>
                <dd>
                    {#typeをtextとしてidを追加#}
                    <input type="text" id="id_name" name="name" size="20" maxlength="16" value="" placeholder="Name" required/>
                </dd>
                {% endcomment %}
                <dt>パスワード</dt>
                <dd>
                    {#typeをpasswordとしてidを追加#}
                    {#minlengthで最小文字数、maxlengthで最大値以上文字を打てなくする。本番環境は6文字以上にする#}
                    <input type="password" id="id_password" name="password" size="20"  minlength="4" maxlength="32" value="" placeholder="Password" style="height:60px;"required/>
                </dd>
            </dl>
            <br>
            <br>
            {# callback関数はtemplates/snippets/grecaptcha.htmlへ #}
            {% include 'snippets/grecaptcha.html' %}
            <br>
            <br>
            <div>
                <input type="submit" id="submit" value="ログインする" style="width:300px;height:70px;" disabled />
            </div>
        </form>
        <br>
        <p>サイトキーエラーの場合は一度reCAPTCHAをリフレッシュして下さい。</p>
        <br>
        <a href=".">reCAPTCHAリフレッシュ<a/>
        {#{{ req }}#}
    </div>
</div>
</body>
</html>

templates/js_test/prep1.html
{# js予習用1 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>js予習用1</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>js予習用1</h1>
    </div>
    <div id="content">
        <div id="lead">
            {% if user.is_authenticated %}
            <p>{{ user.username }}さん御疲れ様です。入力を御願い致します。</p>
            <P></p>
            {% endif %}
        </div>
        <form action="" method="post">
            {#CSRFトークン発行#}
            {% csrf_token %}
            
            <dl>
                {# エラーに原因は各モデルのusernameはUserモデルとForignkeyを貼っているのでここはセレクトボックスのバリューにUserのidを渡す #}
                {#<dt>氏名</dt> type="hidden"とするので隠す#}
                <dd>
                    {#typeをtextとしてidを追加#}
                    {#<input type="text" id="id_username" name="username" size="20" maxlength="16" value="" placeholder="氏名" required/>#}
                    {% if user.is_authenticated %}
                    <input type="hidden" id="id_username" name="username" size="20" maxlength="16" value="{{user.id}}" />
                    {% endif %}
                </dd>
                <dt>認識番号 : 認識番号の下3桁を半角数字で入力して下さい。</dt>
                <p>(例) 10001なら001</p>
                <dd>
                    {#typeをnumberとしてidを追加#}
                    {#<input type="number" id="id_member_number" name="member_number" size="20" maxlength="3" value="" placeholder="組合員番号" required/>#}
                    {#Jsを記述して3桁しか入力できないようにする#}
                    {#styleで幅を指定する#}
                    <input type="number" id="id_member_number" name="member_number" size="20" min="1" max="999" oninput="javascript: this.value = this.value.slice(0, 3);" value="" placeholder="組合員番号" style="width:300px;" required/>
                </dd>
                <dt>西暦(年月) : 西暦(年月)で半角数字6桁で入力して下さい。</dt>
                <p>(例)2010年10月なら201010</p>
                <dd>
                    {#typeをnumberとしてidを追加#}
                    {#<input type="number" id="id_seireki" name="seireki" size="20" minlength="6" maxlength="6" value="" placeholder="年月" required/>#}
                    {#Jsを記述して200001から209912までの6桁でしか入力できないようにする#}
                    {#styleで幅を指定する#}
                    <input type="number" id="id_seireki" name="seireki" size="20" min="200001" max="209912" oninput="javascript: this.value = this.value.slice(0, 6);" value="" placeholder="年月" style="width:300px;" required/>
                </dd>
                <dd>
                    <br>
                    <p>今の時刻です::{{ now_time }}</p>
                    <script>
                        //jsの基本書式
                        /*オブジェクト.メソッド(パラメーター(引数));*/
                        document.write("今の時刻です::{{ now_time }}");
                        //同じスクリプトタグで段落を付ける方法?
                        document.write("<br>ログイン中ユーザーは{{ user.username }}さんです");
                    </script>
                    <br>
                    <script>
                        //str型
                        document.write("1+2");//1+2
                    </script>
                    <br>
                    <script>
                        //int型
                        document.write(1+2);//3
                    </script>
                    <br>
                    <script>
                        //文字列連結(python的)
                        document.write('1+2の結果は',1+2,'です。(Python的)');
                    </script>
                    <br>
                    <script>
                        //文字列連結(php的)
                        document.write('1+2の結果は'+(1+2)+'です。(php的)');
                    </script>
                    <br>
                    <script>
                        //変数
                        //変数の宣言
                        //var 変数名 = 値; ＊同じ変数名の場合var宣言は初回だけ
                        var answer = 2 + 4 ;
                        answer = 7;
                        answer = 2 + 4 ;
                        answer = answer - 1
                        answer += 1//answer = answer + 1
                        document.write('2+4の結果は'+answer+'です');
                    </script>
                    <br>
                    <script>
                        //変数 
                        var answer = 2 + 4 ;
                        //ダブルクウォテーションでも変数は文字列になる
                        document.write("2+4の結果は+answer+です");
                    </script>
                    <br>
                    <script>
                        //変数
                        //テンプレート変数はダブルクウォテーションで値を表示する
                        document.write("現在の時刻は{{ now_time }}です");
                    </script>
                    <br>
                    <script>
                        //オブジェクトとインスタンス
                        //現在の日時を取得してtodayでインスタンス化
                        var today = new Date();
                        //インスタンスを表示(年日時曜日)
                        document.write(today+'<br>');
                        //日だけを取得
                        document.write('今年は'+today.getFullYear()+'です<br>');
                        //getMouth()は0から11の範囲なので1を足す
                        document.write('今月は'+(today.getMonth()+1)+'です<br>');
                        document.write('今日は'+today.getDate()+'です<br>');
                        document.write('時は'+today.getHours()+'です<br>');
                        document.write('分は'+today.getMinutes()+'です<br>');
                        document.write('秒は'+today.getSeconds()+'です<br>');
                        document.write('今の時刻は'+today.getFullYear()+'/'+(today.getMonth()+1)+'/'+today.getDate()+'/'+today.getHours()+':'+today.getMinutes()+':'+today.getSeconds()+'です');

                    </script>
                </dd>
                </dd>
            </dl>
            <br>
            <div>
                {#<input type="submit" value="確定する"/>#}
                <a href="conform/"><input type="submit" style="width:300px;height:70px;" value="確認する"/></a>
                {% if button %}
                {{ user.username }}
                {{ req.seireki }}
                {% endif %}
            </div>
        </form>
        {#{{ req }}#}
        {% comment %}
        UserIDは 
        {{ req.username}}
        です
        {% endcomment %}
    </div>
</div>
</body>
</html>