config/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views 
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index),
    path('login/',views.Login.as_view()),
    path('task_main/',views.task_main),
    path('logout/',LogoutView.as_view()),
    path('extends_block_test/',views.extends_block_test),
    path('report/',include('report.urls')),#report
    path('js_test/',include('js_test.urls')),#js_test
]

report/urls.py
from django.urls import path,include
from report import views

urlpatterns = [
    path('',views.index),#タスク選択画面
    path('cost/',views.cost),#cost入力画面
    path('cost_conform/',views.cost_conform),#costの確認、修正画面
    path('cost_thankyou/',views.cost_thankyou),#costの完了画面
    path('incomes/',views.incomes), 
    #-----models.forms.admin.urls.views.htmlの統合練習用----
    path('test1/',views.test1),
    
    path('sort/',views.sort),#sort入力
    path('sort_conform/',views.sort_conform),#sortの確認・訂正
    path('sort_thankyou/',views.sort_thankyou), 
    
    path('cashbook/',views.cashbook),
    path('cashbook/conform/',views.cashbook_conform),
    path('cashbook/thankyou/',views.cashbook_thankyou),
    
    ###Cashbookモデルのtotalフィールドの総計を取得する
    
    #オリジナル
    path('cashbook_year/',views.cashbook_year),
    #sum関数
    path('cashbook_year_def_sum/',views.cashbook_year_def_sum),
    #生SQL文からの取得
    path('cashbook_year_sql_sum/',views.cashbook_year_sql_sum),
    #-----models.forms.admin.urls.views.htmlの統合練習用----
]

report/models.py
#from tkinter import CASCADE
from tkinter import CASCADE
from django.db import models
#バリデーター
from django.core import validators
#Userモデルの呼び出し
from django.contrib.auth import get_user_model
#Profileモデルの呼び出し
from main.models import Profile

# Create your models here.

#支出のモデル
class Cost(models.Model):
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    seireki = models.IntegerField(null=False,blank=False,validators=[validators.MinValueValidator(200001),validators.MaxValueValidator(299912)])
    koutuuhi = models.IntegerField(default=0,null=False,blank=False)
    shokuhi = models.IntegerField(default=0,null=False,blank=False)
    youfukuhi = models.IntegerField(default=0,null=False,blank=False)
    zeikinn = models.IntegerField(default=0,null=False,blank=False)
    hoken = models.IntegerField(default=0,null=False,blank=False)
    kounetuhi = models.IntegerField(default=0,null=False,blank=False)
    yachin = models.IntegerField(default=0,null=False,blank=False)
    chuushajoudai = models.IntegerField(default=0,null=False,blank=False)
    zapi = models.IntegerField(default=0,null=False,blank=False)
    total = models.IntegerField(null=False,blank=False)
    '''
    def __str__(self):
        #return self.email
        #ここのidもいらない
        return f"{self.username} (番号は{self.member_number}です。)"
        #return self.member_number
    '''

#収入のモデル 
class Incomes(models.Model):
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    seireki = models.IntegerField(null=False,blank=False,validators=[validators.MinValueValidator(200001),validators.MaxValueValidator(299912)])
    salary = models.IntegerField(default=0,null=False,blank=False)
    bonus = models.IntegerField(default=0,null=False,blank=False)
    temporary_income = models.IntegerField(default=0,null=False,blank=False)
    total = models.IntegerField(null=False,blank=False)
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.username}の{self.seireki}収入です"
    

#-----models.forms.admin.urls.views.htmlの統合練習用----

class test1(models.Model):
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    walks = models.IntegerField(default=0,null=False,blank=False,)
    insert_day = models.DateField(help_text='記入日')
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.username}の{self.insert_day}の歩いた歩数です"


#借方モデル←
class Debit(models.Model):
    debit_item = models.CharField(max_length=100)
    
    def __str__(self):
        return f"借方項目は{self.debit_item}です"   

#貸方モデル→
class Credit(models.Model):
    credit_item = models.CharField(max_length=100)
    
    def __str__(self):
        return f"貸方項目は{self.credit_item}です"
    
#仕分けモデル
class Sort(models.Model):
    exec_user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    exec_user_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",)
    exec_day = models.DateField(help_text='仕分実行日')
    debit = models.ForeignKey(Debit,on_delete=models.CASCADE)
    debit_amount = models.IntegerField(null=False,blank=False,)
    credit = models.ForeignKey(Credit,on_delete=models.CASCADE)
    credit_amount = models.IntegerField(null=False,blank=False,)
    comment = models.TextField()
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.exec_day}の{self.comment}の仕分けです"
    
#Costのtotal-Incomeのtotal格納するモデル

###############################################################
#1つのモデルから複数のForeignKeyを使うときは必ずralated_nameを指定する#
###############################################################

#income_totalとcost_totalはreport/views.pyでIncomes,Cost
#モデルでフィルターで値を格納するようにするのでForeignKeyでなく
#IntegerFieldにする(ForeignKeyを使うにはIncomes,Costモデルの
#totalをunique=True,にしなくてはいけなくコレも問題なので)

class Cashbook(models.Model):
    exec_user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name="cashbook_exec_user",)
    exec_user_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",related_name="cashbook_exec_user_number")
    username = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name="cashbook_username")
    member_number = models.ForeignKey(Profile,null=False,blank=False,validators=[validators.MinValueValidator(1),validators.MaxValueValidator(999)],on_delete=models.CASCADE,to_field="member_number",related_name="cashbook_member_number")
    seireki = models.IntegerField(null=False,blank=False,validators=[validators.MinValueValidator(200001),validators.MaxValueValidator(299912)])
    #income_total = models.ForeignKey(Incomes,null=False,blank=False,on_delete=models.CASCADE,to_field="total",) 
    #cost_total = models.ForeignKey(Cost,null=False,blank=False,on_delete=models.CASCADE,to_field="total",)
    income_total = models.IntegerField(null=False,blank=False)
    cost_total = models.IntegerField(null=False,blank=False)
    total = models.IntegerField(null=False,blank=False)
    create_at = models.DateField(auto_now_add=True,)
    update_at = models.DateField(auto_now=True,)
    
    def __str__(self):
        return f"{self.seireki}の{self.username}さんの収支です。実行者は{self.exec_user}です"



#-----models.forms.admin.urls.views.htmlの統合練習用----

    
    
#Chatgtpからのdef __str__関数(特殊関数)の練習用のモデル
class Testchatgtp(models.Model):
    name = models.CharField(max_length=15)
    age = models.IntegerField()
    
    #特殊関数__str__は管理画面などで作成された
    #”モデル名 object”をここで他の文字列で表示します。
    #今回の場合だと作成されたオブジェクト(レコード)に
    #名前と年齢を表示します。
    def __str__(self):
        return f"{self.name} (年齢は{self.age}です)"

report/forms.py
#報告関係reportのフォームを定義

from django import forms
from report.models import Cost,Incomes,test1,Debit,Credit,Sort,Cashbook

#経費フォームの定義
class CostForm(forms.ModelForm):
    class Meta:
        #モデルの指定
        model = Cost
        #入力項目の指定
        fields = {
            'username',
            'member_number',
            'seireki',
            'koutuuhi',
            'shokuhi',
            'youfukuhi',
            'zeikinn',
            'hoken',
            'kounetuhi',
            'yachin',
            'chuushajoudai',
            'zapi',
            'total',
        }
        

#収入フォームの定義
class IncomesForm(forms.ModelForm):
    class Meta:
        model = Incomes
        
        fields = {
            'username',
            'member_number',
            'seireki',
            'salary',
            'bonus',
            'temporary_income',
            'total',
        }
        

#-----models.forms.admin.urls.views.htmlの統合練習用----
#歩数を記録するtest1

class test1Form(forms.ModelForm):
    class Meta:
        model = test1
        fields = {
            'username',
            'member_number',
            'walks',
            'insert_day',
        }

#借方(Debit)
class DebitForm(forms.ModelForm):
    class Meta:
        model = Debit
        fields = {
            'debit_item',
        }
        
#借方(Credit)
class CreditForm(forms.ModelForm):
    class Meta:
        model = Credit
        fields = {
            'credit_item',
        }
        
#仕分(Sort)
class SortForm(forms.ModelForm):
    class Meta:
        model = Sort
        fields = {
            'exec_user',
            'exec_user_number',
            'exec_day',
            'debit',
            'debit_amount',
            'credit',
            'credit_amount',
            'comment',
        }
        
#Cost,Incomesからのtotalを格納するCashbook
class CashbookForm(forms.ModelForm):
    class Meta:
        model = Cashbook
        fields = {
            'exec_user',
            'exec_user_number',
            'username',
            'member_number',
            'seireki',
            'income_total',
            'cost_total',
            'total',
        }
        

#-----models.forms.admin.urls.views.htmlの統合練習用----

templates/report/cashbook_conform.html
{# cashbookの確認・変更画面 #}

{#{{ sort_form.as_p }}#}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>cashbook確認・訂正画面</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>cashbook確認・訂正画面</h1>
    </div>
    <div id="content">
        <div id="lead">
            <p>{{ user.username }}さん、お疲れ様です。cashbookの確認・訂正をして下さい。</p>
            <form action="" method="post">
                {#{{ sort.as_p }}#}{# 動的ファイルを適応する場合はこちら #}
                {% csrf_token %}

                {% if user.is_authenticated %}
                <input type="hidden" name="exec_user" id="id_exec_user" value="{{ exec_user }}">
                <input type="hidden" name="exec_user_number" id="id_exec_user_number" value="{{ exec_user_number }}">
                {% endif %}
                <br>
                <br>
                <p>氏名:</P>
                    <select name="username" required id="id_username">
                        <option value="{{ username }}" selected>{{ user_username_str }}</option>

                        {% for i in user_all_rec %}
                        <option value="{{ i.id }}">{{ i.username }}</option>
                        {% endfor %}
                    
                    </select>
                <br>
                <br>
                <p>識別番号:</P>
                    <select name="member_number" required id="id_member_number">
                        <option value="{{ member_number }}" selected>{{ user_profile_rec }}</option>

                        {% for i in profile_all_rec %}
                        <option value="{{ i.member_number }}">{{ i }}</option>
                        {% endfor %}
                    
                    </select>
                <p>西暦(年月):</p>
                    <input type="number" name="seireki" required id="id_seireki" value="{{ seireki }}">
                <p>月の総収入:</p>
                    <input type="number" name="income_total" required id="id_income_total" value="{{ income_total }}">
                <p>月の総コスト:</p>    
                    <input type="number" name="cost_total" required id="id_cost_total" value="{{ cost_total }}">
                <p>月の総支出:</p>
                    <input type="number" name="total" required id="id_total" value="{{ total }}">
                <br>
                <br>
                <h2>値に問題がある場合はバックスキップで戻って本表を見て下さい</h2>
                <br>
                <br>
                <input type="submit" value="確認・訂正する">

            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/report/cashbook_thankyou.html
{# cashbook完了画面  #}


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>cashbook完了画面</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>cashbook完了画面</h1>
    </div>
    <div id="content">
        <div id="lead">
            <p>{{ user.username }}さん、お疲れ様です。cashbookの格納が完了しました。</p>
            
        </div>
    </div>
</div>
</body>
</html>

templates/report/cost.html
{# 支出の入力ページです #}

{# ログイン画面 PHP版組合アプリからの流用 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>経費入力</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>経費入力</h1>
    </div>
    <div id="content">
        <div id="lead">
            <p>{{ user.username }}さん、お疲れ様です。経費報告の入力をよろしくお願いいたします。</p>
            <form action="" method="post">
                {#{{ cost_form.as_p }}#}{# 動的ファイルを適応する場合はこちら #}
                {% csrf_token %}

                {% if user.is_authenticated %}
                <input type="hidden" name="username" id="id_username" value="{{ user.id }}">
                <input type="hidden" name="member_number" id="id_member_number" value="{{ profile_member_number }}">
                {% endif %}
                <br>
                <p>年月(2002年07月なら200207):</P>
                <input type="number" name="seireki" id="id_seireki" placeholder="YYYY/MM" value="" required />
                <br>
                <p>交通費:</P>
                <input type="number" name="koutuuhi" id="id_koutuuhi" placeholder="交通費" value="" required />
                <br>
                <p>食費:</P>
                <input type="number" name="shokuhi" id="id_shokuhi" placeholder="食費" value="" required />
                <br>
                <p>洋服費:</P>
                <input type="number" name="youfukuhi" id="id_youfukuhi" placeholder="洋服費" value="" required />
                <br>
                <p>税金:</P>
                <input type="number" name="zeikinn" id="id_zeikinn" placeholder="税金" value="" required />
                <br>
                <p>保険:</P>
                <input type="number" name="hoken" id="id_hoken" placeholder="保険" value="" required />
                <br>
                <p>光熱費:</P>
                <input type="number" name="kounetuhi" id="id_kounetuhi" placeholder="光熱費" value="" required />
                <br>
                <p>家賃:</P>
                <input type="number" name="yachin" id="id_yachin" placeholder="家賃" value="" required />
                <br>
                <p>駐車場代:</P>
                <input type="number" name="chuushajoudai" id="id_chuushajoudai" placeholder="駐車場代" value="" required />
                <br>
                <p>雑費:</P>
                <input type="number" name="zapi" id="id_zapi" placeholder="雑費" value="" required />
                <br>
                {#<p>合計:</P>#}
                <input type="hidden" name="total" id="id_total" placeholder="合計総額" value="0" required />
                <br>
                <br>
                <input type="submit" value="確定する">

            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/report/cost_conform.html
{# 支出の入力ページです #}

{# ログイン画面 PHP版組合アプリからの流用 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>経費確認・訂正画面</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>経費確認・訂正画面</h1>
    </div>
    <div id="content">
        <div id="lead">
            <p>{{ user.username }}さん、お疲れ様です。経費報告の入力をよろしくお願いいたします。</p>
            <form action="" method="post">
                {#{{ cost_form.as_p }}#}{# 動的ファイルを適応する場合はこちら #}
                {% csrf_token %}

                {% if user.is_authenticated %}
                <input type="hidden" name="username" id="id_username" value="{{ user.id }}">
                <input type="hidden" name="member_number" id="id_member_number" value="{{ member_number }}">
                {% endif %}
                <br>
                <p>年月(2002年07月なら200207):</P>
                <input type="number" name="seireki" id="id_seireki" placeholder="YYYY/MM" value="{{ seireki }}" required />
                <br>
                <p>交通費:</P>
                <input type="number" name="koutuuhi" id="id_koutuuhi" placeholder="交通費" value="{{ koutuuhi }}" required />
                <br>
                <p>食費:</P>
                <input type="number" name="shokuhi" id="id_shokuhi" placeholder="食費" value="{{ shokuhi }}" required />
                <br>
                <p>洋服費:</P>
                <input type="number" name="youfukuhi" id="id_youfukuhi" placeholder="洋服費" value="{{ youfukuhi }}" required />
                <br>
                <p>税金:</P>
                <input type="number" name="zeikinn" id="id_zeikinn" placeholder="税金" value="{{ zeikinn }}" required />
                <br>
                <p>保険:</P>
                <input type="number" name="hoken" id="id_hoken" placeholder="保険" value="{{ hoken }}" required />
                <br>
                <p>光熱費:</P>
                <input type="number" name="kounetuhi" id="id_kounetuhi" placeholder="光熱費" value="{{ kounetuhi }}" required />
                <br>
                <p>家賃:</P>
                <input type="number" name="yachin" id="id_yachin" placeholder="家賃" value="{{ yachin }}" required />
                <br>
                <p>駐車場代:</P>
                <input type="number" name="chuushajoudai" id="id_chuushajoudai" placeholder="駐車場代" value="{{ chuushajoudai }}" required />
                <br>
                <p>雑費:</P>
                <input type="number" name="zapi" id="id_zapi" placeholder="雑費" value="{{ zapi }}" required />
                <br>
                <br>
                <p>合計:</P>
                <p name="total" id="id_total" >{{ total }}</p>
                <br>
                <br>
                <input type="submit" value="確定する">

            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/report/sort.html
{# 仕分の入力画面です #}
{#{{ sort_form.as_p }}#}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>仕分入力</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>仕分入力</h1>
    </div>
    <div id="content">
        <div id="lead">
            <p>{{ user.username }}さん、お疲れ様です。仕分の入力をよろしくお願いいたします。</p>
            <form action="" method="post">
                {#{{ sort.as_p }}#}{# 動的ファイルを適応する場合はこちら #}
                {% csrf_token %}

                {% if user.is_authenticated %}
                <input type="hidden" name="exec_user" id="id_exec_user" value="{{ user_id }}">
                <input type="hidden" name="exec_user_number" id="id_exec_user_number" value="{{ user_number }}">
                {% endif %}
                <br>
                <p>実行日:</P>
                <input type="date" name="exec_day" id="id_exec_day" placeholder="YYYY/MM/DD" value="" required />
                <br>
                <br>
                <p>借方項目:</P>
                {#<input type="number" name="debit" id="id_debit" placeholder="-----" value="" required />#}
                <select name="debit" required id="id_debit">
                    <option value="" selected>---------</option>
                    
                    {# ここからfor文で回していく #}
                    {% for i in  debit_val %}
                    <option value="{{ i.id }}">借方項目は{{ i.debit_item }}です</option>
                    {% endfor %}
                    {% comment %}
                    {# 静的ファイルでの作成 sort.as_pからのコピー #}
                    <option value="1">貸方項目は売上です</option>
                  
                    <option value="2">貸方項目は仕入です</option>
                  
                    <option value="3">貸方項目は現金です</option>
                  
                    <option value="4">貸方項目は普通預金です</option>
                  
                    <option value="5">貸方項目は当座預金です</option>
                  
                    <option value="6">貸方項目は支払い手数料です</option>
                  
                    <option value="7">貸方項目は売掛金です</option>
                  
                    <option value="8">貸方項目は買掛金です</option>
                  
                    <option value="9">貸方項目は未払金です</option>
                  
                    <option value="10">貸方項目は車両運搬具です</option>
                  
                    <option value="11">貸方項目は発送費です</option>
                    {% endcomment %}
                </select>
                <br>
                <br>
                <p>借方金額:</P>
                <input type="number" name="debit_amount" id="id_debit_amount" placeholder="" value="" required />
                <br>
                <br>
                <p>貸方項目:</P>
                {# ここから続き #}
                {#<input type="number" name="credit" id="id_credit" placeholder="-----" value="" required />#}

                <select name="credit" required id="id_credit">
                    <option value="" selected>---------</option>
                    
                    {# ここからfor文で回していく #}
                    {% for i in  credit_val %}
                    <option value="{{ i.id }}">貸方項目は{{ i.credit_item }}です</option>
                    {% endfor %}
                </select>

                <br>
                <br>
                <p>貸方金額:</P>
                <input type="number" name="credit_amount" id="id_credit_amount" placeholder="" value="" required />
                <br><br>
                <p>仕分内容:</P>
                <input type="text" name="comment" id="id_comment" placeholder="仕分内容を入れて下さい" value="" required />
                <br>
                <br>
                <input type="submit" value="確認・訂正する">

            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/report/sort_conform.html
{# 仕分の確認・訂正画面です #}

{#{{ sort_form.as_p }}#}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>仕分確認・訂正</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>仕分確認・訂正</h1>
    </div>
    <div id="content">
        <div id="lead">
            <p>{{ user.username }}さん、お疲れ様です。仕分の確認・訂正をよろしくお願いいたします。</p>
            <form action="" method="post">
                {#{{ sort.as_p }}#}{# 動的ファイルを適応する場合はこちら #}
                {% csrf_token %}

                {% if user.is_authenticated %}
                <input type="hidden" name="exec_user" id="id_exec_user" value="{{ exec_user }}">
                <input type="hidden" name="exec_user_number" id="id_exec_user_number" value="{{ exec_user_number }}">
                {% endif %}
                <br>
                <p>実行日:</P>
                <input type="date" name="exec_day" id="id_exec_day" placeholder="YYYY/MM/DD" value="{{ exec_day }}" required />
                <br>
                <br>
                <p>借方項目:</P>
                {#<input type="number" name="debit" id="id_debit" placeholder="-----" value="" required />#}
                <select name="debit" required id="id_debit">
                    {#<option value="" selected>---------</option>#}

                    {# セッションを受け取りセッション値とdebit_valのidが一致なら先頭に表示 #}
                    {% for i in  debit_val %}
                    {% if i.id ==  debit  %}
                    <option value="{{ i.id }}" selected>借方項目は{{ i.debit_item }}です</option>
                    {% endif %}
                    {% endfor %}

                    {# 区切り #}
                    {#<option value="" >---------</option>#}

                    {# セッション値とdebit_valのidが一致していないときの処理 #}
                    {% for i in  debit_val %}
                    {% if i.id !=  debit  %}
                    <option value="{{ i.id }}">借方項目は{{ i.debit_item }}です</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <br>
                <br>
                <p>借方金額:</P>
                <input type="number" name="debit_amount" id="id_debit_amount" placeholder="" value="{{ debit_amount }}" required />
                <br>
                <br>
                <p>貸方項目:</P>
                {# ここから続き #}
                {#<input type="number" name="credit" id="id_credit" placeholder="-----" value="" required />#}

                <select name="credit" required id="id_credit">
                    {#<option value="" selected>{{ credit }}</option>#}
                    {% comment %}
                    {% for i in credit_val %}
                    {% if i.id == credit %}
                    <option value="{{ credit }}" selected>貸方項目は{{ i.credit_item }}です</option>
                    {% endif %}
                    {% endfor %}

                    <option value="" >---------</option>
                    {% endcomment %}
                    
                    {# ここからfor文で回していく #}
                    {% for i in  credit_val %}
                    {% if i.id ==  credit  %}
                    <option value="{{ credit }}" selected>貸方項目は{{ i.credit_item }}です</option>
                    {#<option value="">---------</option>#}
                    {% elif i.id != credit %}
                    <option value="{{ i.id }}">貸方項目は{{ i.credit_item }}です</option>
                    {% endif %}
                    {% endfor %}
                    
                </select>

                <br>
                <br>
                <p>貸方金額:</P>
                <input type="number" name="credit_amount" id="id_credit_amount" placeholder="" value="{{ credit_amount }}" required />
                <br><br>
                <p>仕分内容:</P>
                <input type="text" name="comment" id="id_comment" placeholder="仕分内容を入れて下さい" value="{{ comment }}" required />
                <br>
                <br>
                <input type="submit" value="確認・訂正する">

            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/report/sort_thankyou.html
{# 仕分の完了画面です #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    {% load  static %}    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
    <title>仕分入力完了画面</title>
</head>
<body>
<div id="wrap">
    <div id="head">
        <h1><a href="/"><a/>仕分入力完了画面</h1>
    </div>
    <div id="content">
        <div id="lead">
            <p>{{ user.username }}さん、お疲れ様です。仕分の入力が完了しました。</p>
            
        </div>
    </div>
</div>
</body>
</html>